app:
  title: Backstage Example App
  baseUrl: ${APP_BASE_URL}
  experimental:
    packages: all

  support:
    url: https://github.com/backstage/backstage/issues
    items:
      - title: Issues
        icon: github
        links:
          - url: https://github.com/backstage/backstage/issues
            title: GitHub Issues
      - title: Discord Chatroom
        icon: chat
        links:
          - url: https://discord.gg/backstage-687207715902193673
            title: '#backstage'

  packageName: example-app

backend:
  baseUrl: ${BACKEND_BASE_URL}
  listen:
    port: 7007

  auth:
    dangerouslyDisableDefaultAuthPolicy: true
    session:
      secret: ${AUTH_SESSION_SECRET}

  database:
    client: pg
    connection:
      host: ${PGHOST}
      port: ${PGPORT}
      user: ${PGUSER}
      password: ${PGPASSWORD}
      database: ${PGDATABASE}

  cors:
    origin: ${APP_BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

  csp:
    connect-src: ["'self'", 'http:', 'https:']

  reading:
    allow:
      - host: example.com
      - host: '*.mozilla.org'

auth:
  environment: development
  session:
    secret: ${AUTH_SESSION_SECRET}
  providers:
    adfs:
      development:
        clientId: ${AUTH_ADFS_CLIENT_ID}
        clientSecret: ${AUTH_ADFS_CLIENT_SECRET}
        authorizationUrl: ${ADFS_AUTHORIZATION_URL}
        tokenUrl: ${ADFS_TOKEN_URL}
        callbackUrl: ${AUTH_ADFS_CALLBACK_URL}
        scope: 'openid profile email'

scaffolder:
  defaultAuthor:
    name: Scaffolder
    email: scaffolder@backstage.io
  defaultCommitMessage: 'Initial commit'

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, API, Resource, System, Domain, Location]
  locations:
    - type: file
      target: ../catalog-model/examples/all.yaml
    - type: file
      target: ../catalog-model/examples/acme-corp.yaml
      rules:
        - allow: [User, Group]
    - type: file
      target: ../../plugins/github-actions/examples/sample.yaml
    - type: file
      target: ../../plugins/techdocs-backend/examples/documented-component/catalog-info.yaml
    - type: file
      target: ../../plugins/adr/examples/component/catalog-info.yaml
    - type: file
      target: ../../plugins/scaffolder-backend/sample-templates/all-templates.yaml
      rules:
        - allow: [Template]
  providers:
    backstageOpenapi:
      plugins:
        - catalog
        - search

techdocs:
  builder: local
  generator:
    runIn: docker
  publisher:
    type: local

proxy:
  endpoints:
    '/pagerduty':
      target: https://api.pagerduty.com
      headers:
        Authorization: Token token=${PAGERDUTY_TOKEN}

organization:
  name: My Company

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
  gitlab:
    - host: gitlab.com
      token: ${GITLAB_TOKEN}
  azure:
    - host: dev.azure.com
      token: ${AZURE_TOKEN}
  awsS3:
    - endpoint: ${AWS_S3_ENDPOINT}
      accessKeyId: ${AWS_ACCESS_KEY_ID}
      secretAccessKey: ${AWS_SECRET_ACCESS_KEY}

permission:
  enabled: true
